services:
  - type: web
      name: pagina-11
          runtime: node
              buildCommand: npm install
                  startCommand: npm start
                      envVars:
                            - key: NODE_ENV
                                    value: production
                                          - key: PORT
                                                  value: 3000
